//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUser
    {
        public ProjectUser()
        {
            this.Action = new HashSet<Action>();
            this.Rating = new HashSet<Rating>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ExternalId { get; set; }
    
        public virtual ICollection<Action> Action { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
